server:
  port: 8082

spring:
  application:
    name: notification-service

  config:
    import: "configserver:"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
